name: "@joeir"
title: "lé blog"
description: "Lest I forget"
host: github-blog.joeir.net
encoding: UTF-8
future: true
google_analytics: UA-75287781-5
kramdown:
   input: GFM
   hard_wrap: false
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
permalink: pretty
remote_theme: zephinzer/mediumish-theme-jekyll
timezone: Asia/Singapore